### ISSUE TITLE
OS and nvidia cuda driver version

### ISSUE THREAD

**Issue by townim-faisal** [luulinh90s/Neural-Baby-Talk-python3#12]
It will be really helpful if you tell your ubuntu version and nvdia cuda driver, cuda toolkit version where you have run this code

**Comment by giangnguyen2412** [comment]
I was using Ubuntu 16.04 and for other information, they are exactly included in this [file](https://github.com/luulinh90s/Neural-Baby-Talk-python3/blob/master/environment.yml)

**Comment by townim-faisal** [comment]
Can you tell me your pc configuration and how much time was needed for training?

**Comment by giangnguyen2412** [comment]
The training environment includes one Nvidia TitanX GPU and an Intel(R) Core(TM) i7 4.0 GHz PC with 16GB RAM, running Ubuntu 16.04 LTS (64-bit).
