### ISSUE TITLE
is it possible to use gtx2060

### ISSUE THREAD

**Issue by uchchwas1** [luulinh90s/Neural-Baby-Talk-python3#14]
For cuda 9.0 have to install nvidia drive ( 348-396). But, For 2060 all available drivers are above 400.
Can i install cuda 9.0, cudnn 7.3 and nvidia driver 415?

**Comment by townim-faisal** [comment]
Yes it is possible, but before compile the roi_align with provided environment's version of cuda 9.0, cudnn 7.3 in system, then copy that compiled version to your main folder. Then you can run anything in the provided conda environment. It will not conflict if your system has cuda 10.1.

**Comment by uchchwas1** [comment]
Thank you, you save my day :+1:
