### ISSUE TITLE
how to use demo.py

### ISSUE THREAD

**Issue by BillLZD** [luulinh90s/Neural-Baby-Talk-python3#2]
Excuse,me. I ran demo.py. 
The captions are very strange.
However,the detection part performs well.
Besides, the objects detected in the photo have no relationship with the corresponding caption. The objects don't appera in the caption.
Why the demo.py generates captions like this?

ID:184386 sentence: wipe [ bulldog ] doing wipe afraid form payer wipe afraid form 
ID:231037 sentence: wipe [ ship ] undergoing wipe [ baseball bat ] outdoor heating rubs wipe animal 
ID:467437 sentence: wipe [ ship ] serene outdoor wipe [ bulldog ] doing wipe [ ship ] 
ID:258588 sentence: wipe [ ship ] corsage wipe afraid reflected payer cub housed stitch kids 
ID:460251 sentence: wipe [ clock ] converses skating outdoor heating rubs wipe moped tried 
ID:357978 sentence: wipe hull rubs [ bagel ] preparation carved wipe tried 
ID:571641 sentence: wipe alive receiver doing wipe alive payer wipe [ pontoon ] 
ID:163348 sentence: wipe [ schnauzer ] payer wipe [ pontoon ] outdoor wipe receiver 
ID:298978 sentence: wipe [ jetliner ] skating corsage wipe thermos doing wipe [ macbook ] 
ID:258628 sentence: wipe [ ship ] horns stitch kids outdoor wipe western 
ID:118432 sentence: wipe hull rubs [ bagel ] preparation outdoor heating rubs wipe bins bubbles [ cockatoo ] 
ID:205230 sentence: wipe hull rubs [ kids ] skating carved wipe [ cupcake ] 
ID:345136 sentence: wipe civilians [ walker ] skating corsage wipe bins doing wipe prints payer afraid [ cockatoo ] 
ID:404613 sentence: wipe [ kid ] horns sprout wipe [ foal ] corsage wipe bins 
ID:131089 sentence: wipe chalk [ walker ] horns stitch doing wipe ceramics 
ID:432570 sentence: wipe [ biker ] doing who corsage reception skating outdoor wipe tried 
ID:214224 sentence: wipe [ jetliner ] horns preparation session wipe southeast doing wipe envelopes rubs [ skateboarded ] 
ID:199764 sentence: wipe hull rubs [ bagel ] preparation carved wipe tried doing wipe rugs 
ID:176312 sentence: wipe [ jetliner ] preparation corsage dandelion rubs wipe served sprout wipe [ firetruck ] 
ID:453297 sentence: wipe [ firetruck ] horns skating outdoor wipe tried bathtub useful wipe terminal 
ID:529668 sentence: wipe [ jetliner ] sprout wipe [ firetruck ] corsage dandelion rubs wipe rugs 
ID:551107 sentence: wipe civilians [ traffic light ] preparation corsage dandelion rubs wipe [ macbook ] 
ID:413120 sentence: wipe inspired [ biker ] fun doing prints removing uneaten 
ID:369771 sentence: wipe straining rubs crotch doing wipe [ ski ] rubs crotch payer wipe [ ski ] rubs standing

**Comment by giangnguyen2412** [comment]
I am sorry for late reply, have not noticed so far :( Did you solve the problem, I am running normally and I think may you did not run preprocessing step (or you just need to download the preprocessed data and put into data/coco/)

**Comment by giangnguyen2412** [comment]
Download them from this: https://www.dropbox.com/s/1t9nrbevzqn93to/coco.tar.gz?dl=0

**Comment by giangnguyen2412** [comment]
![Capture](https://user-images.githubusercontent.com/30857111/56470126-806fa200-647d-11e9-8b49-584e1ab5a032.JPG)
What I am getting now

**Comment by giangnguyen2412** [comment]
![Capture](https://user-images.githubusercontent.com/30857111/56470874-638b9c80-6486-11e9-9220-87c4ee4be433.JPG)
When running evaluation

**Comment by wlybug** [comment]
I ran into the same problem, but not the reason you mentioned above.

**Comment by giangnguyen2412** [comment]
Here I see that the textual caption and visual caption are both wrong? If you just run demo.py without any modification, I dont have any clues why you get this..

**Comment by wlybug** [comment]
The image can be detected normally but the title generation is not the detected one.for example
eg:a [ backpack ] on a [ cheesecake ] on a street。
But the picture does not detect the two words， [ backpack ] ， [ cheesecake ]，But it’s detected as a person。

**Comment by giangnguyen2412** [comment]
Yeah, correct! I am re-running and see that textual caption is correct but visual caption is wrong, I put another here but I dont expect the answer from the author tbh, since he has not reply any issues for long 
https://github.com/jiasenlu/NeuralBabyTalk/issues/43

**Comment by giangnguyen2412** [comment]
I am trying to figure out, If any progress, I will let you know

**Comment by wlybug** [comment]
thank you very much

**Comment by jhhuang96** [comment]
@wlybug  hi, I encountered the same issue that correct sentence template but incorrect visual words by detector. So how can I fix it?

**Comment by PRYUS** [comment]
Hey @luulinh90s  ! 
Have you been able to run the demo on a custom image? Kindly let me know if you have.

**Comment by giangnguyen2412** [comment]
I think if we use the custom image, the object in the image and the object proposals provided by the author are not match, then the result will be incorrect. Anyway, I still can't, you should contact the author for the answer tbh :(

**Comment by RamatovInomjon** [comment]
Hi, can anyone help me to run the demo please? 
![image](https://user-images.githubusercontent.com/43458270/62541488-7470ea00-b88c-11e9-8f87-dd72bb1ed582.png)

**Comment by RamatovInomjon** [comment]
I didn't understand what should I enter to continue

**Comment by RamatovInomjon** [comment]
@luulinh90s Can you guide please? what  I'm doing wrong?

**Comment by giangnguyen2412** [comment]
@RamatovInomjon you just need to press `c` then enter to continue the program or simply press Ctrl-D

**Comment by RamatovInomjon** [comment]
@luulinh90s thanks for your quick reply, it is started downloading .vector_cache/glove.6B.zip file,  I open the code but didn't get what this file for? thanks for your time again

**Comment by giangnguyen2412** [comment]
This file is for word embedding, its nice to use this or you can choose what embedding tool you want rather than GloVE

**Comment by RamatovInomjon** [comment]
@luulinh90s thanks for support
