### ISSUE TITLE
where can I find infos_-best.pkl ?

### ISSUE THREAD

**Issue by lfeelf** [luulinh90s/Neural-Baby-Talk-python3#6]
Copy model-best.pth and infos_-best.pkl (from save/ dir)to NeuralBabyTalk/

I cloned this project and follow steps to running demo.py but I cannot find infos_-best.pkl.
Should I train the model before I running demo.py?

**Comment by giangnguyen2412** [comment]
model-best.pth and infos_-best.pkl are obtained from training, so you can get pretrained files here: https://www.dropbox.com/s/6buajkxm9oed1jp/coco_nbt_1024.tar.gz?dl=0

You dont need to train the model to run demo.py, just you the pretrained model I sent.

**Comment by lfeelf** [comment]
ok, thank you for your help.
and I have two more questions
do you know is *.h5 contains pre-detection result or not?
how to replace detection to another detection?

**Comment by giangnguyen2412** [comment]
Im sorry for late reply. For your questions:
`do you know is *.h5 contains pre-detection result or not?`
Yes, .h5 is the pre-detection RoI result.
`how to replace detection to another detection?`
In Encoder, you can simply change the CNN architectecture (now the code is supporting resnet and vgg). For RoIs, you can use any detectors and then save to h5 file for later usage.
