### ISSUE TITLE
ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead.

### ISSUE THREAD

**Issue by pujanm** [luulinh90s/Neural-Baby-Talk-python3#7]
Hi @luulinh90s,
I am facing this issue with pytorch version 1.2.0 can you help me out with this and I am using Python version 3.6.5?
<img width="1580" alt="Screenshot 2019-10-04 at 12 31 36 AM" src="https://user-images.githubusercontent.com/26873907/66156031-7feb5200-e63e-11e9-986e-4c6b38a8fefc.png">

These are the versions of the other tools:
```
certifi==2019.9.11
chardet==3.0.4
cycler==0.10.0
decorator==4.4.0
idna==2.8
imageio==2.5.0
kiwisolver==1.1.0
matplotlib==3.1.1
networkx==2.3
numpy==1.17.2
pandas==0.25.1
Pillow==6.2.0
psutil==5.6.3
pyparsing==2.4.2
python-dateutil==2.8.0
pytz==2019.2
PyWavelets==1.0.3
PyYAML==5.1.2
requests==2.22.0
scikit-image==0.15.0
scipy==1.3.1
six==1.12.0
stanfordcorenlp==3.9.1.1
torch==1.2.0
torchtext==0.4.0
torchvision==0.4.0
tqdm==4.36.1
urllib3==1.25.6
```

**Comment by giangnguyen2412** [comment]
ffi has been deprecated. Please refer this https://github.com/pytorch/pytorch/issues/15645

**Comment by joyce9533** [comment]
> Hi @luulinh90s,
> I am facing this issue with pytorch version 1.2.0 can you help me out with this and I am using Python version 3.6.5?
> <img alt="Screenshot 2019-10-04 at 12 31 36 AM" width="1580" src="https://user-images.githubusercontent.com/26873907/66156031-7feb5200-e63e-11e9-986e-4c6b38a8fefc.png">
> 
> These are the versions of the other tools:
> 
> ```
> certifi==2019.9.11
> chardet==3.0.4
> cycler==0.10.0
> decorator==4.4.0
> idna==2.8
> imageio==2.5.0
> kiwisolver==1.1.0
> matplotlib==3.1.1
> networkx==2.3
> numpy==1.17.2
> pandas==0.25.1
> Pillow==6.2.0
> psutil==5.6.3
> pyparsing==2.4.2
> python-dateutil==2.8.0
> pytz==2019.2
> PyWavelets==1.0.3
> PyYAML==5.1.2
> requests==2.22.0
> scikit-image==0.15.0
> scipy==1.3.1
> six==1.12.0
> stanfordcorenlp==3.9.1.1
> torch==1.2.0
> torchtext==0.4.0
> torchvision==0.4.0
> tqdm==4.36.1
> urllib3==1.25.6
> ```

have you solved the problem?

**Comment by joyce9533** [comment]
> ffi has been deprecated. Please refer this [pytorch/pytorch#15645](https://github.com/pytorch/pytorch/issues/15645)

sorry, the methods in this link didn't work for me.. do you have another idea to solve the problem or do you know which file should I modify to make this work?

**Comment by horanyinora** [comment]
Any update? I ran into the same problem using the conda environment you provided. I tried to downgrade PyTorch too but it did not solve my issue either. How could we solve this problem?
Thanks in advance!

**Comment by joyce9533** [comment]
Unfortunately not. I've already give it up. I search on Google about this project, it seems that no one can really achieve it. I think maybe its environment is too complicated to achieve. But I like the idea in this paper, I decide to build the model myself. Hope you good luck!


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Nora Horanyi"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月11日(星期三) 晚上10:57
收件人:&nbsp;"luulinh90s/Neural-Baby-Talk-python3"<Neural-Baby-Talk-python3@noreply.github.com&gt;;
抄送:&nbsp;"lin"<503424587@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [luulinh90s/Neural-Baby-Talk-python3] ImportError: torch.utils.ffi is deprecated. Please use cpp extensions instead. (#7)




Any update? I ran into the same problem using the conda environment you provided. I tried to downgrade PyTorch too but it did not solve my issue either. How could we solve this problem?
 Thanks in advance!
