### ISSUE TITLE
How to extract regions using my own reimplementation of faster rcnn code?

### ISSUE THREAD

**Issue by Cathyttt** [luulinh90s/Neural-Baby-Talk-python3#8]
Hello. Can you release the format of bounding box data?
> You can also extract using our reimplementation of faster rcnn code, or any exsiting detection framework. The format of bounding box data will added later.

**Comment by giangnguyen2412** [comment]
May you should contact the author. I am not the author of this paper.

Vào 12:23, T.5, 31 Th10, 2019 Cathyttt <notifications@github.com> đã viết:
